version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db_kitty:
    container_name: db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db_kitty
    container_name: backend
#    image: ozziken/kittygram_backend
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    container_name: frontend
    env_file: .env
#    image: ozziken/kittygram_frontend
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    container_name: gateway
#    image: ozziken/kittygram_gateway
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
